// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB21gHCy8b6TbYewx0189EEOYNzo0oIzQM',
    appId: '1:199216913951:web:365cb23be0747e4084ff2a',
    messagingSenderId: '199216913951',
    projectId: 'store-backend-93d66',
    authDomain: 'store-backend-93d66.firebaseapp.com',
    storageBucket: 'store-backend-93d66.firebasestorage.app',
    measurementId: 'G-VH6SG8QMVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRv3sVlX1-XzAGi8jQ90ABE7h3pjjRKQ',
    appId: '1:199216913951:android:a3d9c5cc1adb866a84ff2a',
    messagingSenderId: '199216913951',
    projectId: 'store-backend-93d66',
    storageBucket: 'store-backend-93d66.firebasestorage.app',
  );
}
